apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mortis-consul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: mortis-consul:001
        ports:
        - containerPort: 8500