apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mortis-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: mortis-redis:001
        ports:
        - containerPort: 6379