apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    name: data-redis
    targetPort: 6379
    nodePort: 31379
  selector:
    app: redis