apiVersion: v1
kind: Service
metadata:
  name: mortis-redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - name: data-redis
      protocol: "TCP"
      port: 6379
      targetPort: 6379
      nodePort: 31379
  selector:
    app: redis