apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mortis-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mortis-mysql:001
        ports:
        - containerPort: 3306
          hostPort: 3306