apiVersion: v1
kind: Service
metadata:
  name: mortis-mysql
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - name: data-mysql
      protocol: "TCP"
      port: 3306
      targetPort: 3306
      nodePort: 31306
  selector:
    app: mysql